dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"

addons:

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
  - npm i -g npm@5.3.0

install:
  - npm install

script:
  - npm run ng test -- --single-run=true --browsers Chrome