dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

branches:
  only:
  - develop
  - /^release\/.*$/

cache:
  directories:
    - "node_modules"

addons:

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
  - npm i -g npm@5.3.0

install:
  - npm install

script:
  - npm run ng test -- --single-run=true --browsers Chrome
  - if [ "$TRAVIS_BRANCH" =~ ^release\/.*$ ]; then npm run ng build --prod; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run ng build --dev; fi

before_deploy: "echo 'ready?'"

deploy:
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    slot: ng2contactsapp-dev
    on: 
      branch: develop
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    slot: ng2contactsapp-staging
    on:
      all_branches: true